### PR TITLE
Pushing changes

### PR DESCRIPTION
**Pull request by patdavid**
I've added your fork as a sub-directory of presentation material for the base repo:
`./foss-photography-presentations-master/`

This is just for organization.  I'm issuing the PR so it can be kept up-to-date. :)

### CODE REVIEW

**Comment by paperdigits** [comment]
Interesting, I didn't get an email notification for this PR either...

**Comment by paperdigits** [comment]
@patdavid Do you want to keep the finished presentation at the top level of the repo?

**Comment by patdavid** [comment]
@paperdigits which presentation?  I've been keeping the individual presentation in their own folders and linking to them from the main README of the repo.

Speaking of which, we should probably include details on the main README page to point new users to your sub-folder of work with "presentations-master" so they can get up and running quickly.  I have no problem doing this - just need a little time to get it setup and run it by you first.

**Comment by paperdigits** [comment]
All of the presentations! :) I'll move a few things around and send another (smaller) PR, since there are some redundant things in my presentation subfolder.

**Pull request merged**
